### ISSUE TITLE
Passing through options to RCurl

### ISSUE THREAD

**Issue by jonclayden** [adigherman/Rxnat#11]
Hi Adi, and many thanks for creating this package!

I need to communicate with our XNAT server through a proxy, so I was wondering whether it would be practical for `xnat_connect()` to gain a mechanism to pass options through to `RCurl::curlPerform()`? I can't see any other way of making a connection or passing an existing one to the package's functions.

**Comment by adigherman** [comment]
Hi Jon,

I've updated the package. Do you mind giving it a try and letting me know if it worked for you as expected. Then, I can push to CRAN.

**Comment by jonclayden** [comment]
Many thanks for looking at this! It may be user error(?), but when I perform

```r
ucl <- xnat_connect(url, user, pass, "UCL", proxy="socks4://127.0.0.1:1080")
```

I get a timeout, but for example

```r
RCurl::getURL(file.path(url,"data","projects"), .opts=list(username=user, password=pass, proxy="socks4://127.0.0.1:1080"))
```

gives me the JSON list of projects output as expected.

**Comment by jonclayden** [comment]
It looks like the ellipsis may be missing [here](https://github.com/adigherman/Rxnat/blob/4bcd776aac0f563278e0f606c3cf249bc87b3f88/R/xnat_api.R#L645) and [here](https://github.com/adigherman/Rxnat/blob/4bcd776aac0f563278e0f606c3cf249bc87b3f88/R/xnat_api.R#L660).

**Comment by adigherman** [comment]
Jon, you are absolutely right. Thanks for fixing it, please send the PR my way :)
